name: Extract Backend Zip

on:
  push:
    paths:
      - 'backend.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip backend.zip
        run: |
          unzip -o backend.zip -d ./backend
          rm backend.zip

      - name: Commit extracted backend
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add backend
          git commit -m "Extracted backend.zip via GitHub Action"
          git push
